stages:
  - lint
  - test
  - deploy

variables:
  legacy_pkgs: >-
    ./node
    ./node/api
    ./node/api/server
  package_pkgs: >-
    ./build
    ./cmd/sia-node-scanner
    ./cmd/siac
    ./cmd/siad
    ./compatibility
    ./crypto
    ./encoding
    ./modules
    ./modules/consensus
    ./modules/explorer
    ./modules/feemanager
    ./modules/gateway
    ./modules/host
    ./modules/host/contractmanager
    ./modules/host/mdm
    ./modules/renter
    ./modules/renter/contractor
    ./modules/renter/filesystem
    ./modules/renter/filesystem/siafile
    ./modules/renter/filesystem/siadir
    ./modules/renter/hostdb
    ./modules/renter/hostdb/hosttree
    ./modules/renter/proto
    ./modules/renter/skynetblacklist
    ./modules/renter/skynetportals
    ./modules/miner
    ./modules/wallet
    ./modules/transactionpool
    ./persist
    ./sync
    ./skykey
    ./types
  siatest_pkgs: >-
    ./siatest
    ./siatest/consensus
    ./siatest/daemon
    ./siatest/feemanager
    ./siatest/gateway
    ./siatest/host
    ./siatest/miner
    ./siatest/transactionpool
    ./siatest/wallet
  siatest_renter_pkgs: >-
    ./siatest/renter
  siatest_renter_sub_pkgs: >-
    ./siatest/renter/contractor
    ./siatest/renter/hostdb
    ./siatest/renterhost

default: &default_params
  ## Run tests with most recent golang version to take advantage of any perf
  ## improvements.
  image: golang:1.13.8
  before_script:
    - mkdir -p .cache/gocache
    - export PATH=$PATH:$CI_PROJECT_DIR/.cache/bin/
    - export GOPATH="$CI_PROJECT_DIR/.cache"

## Default params for Windows runner
.default_windows: &default_windows_params
  before_script:
    - $env:USERNAME
    ## No need to use gitlab cache on dedicated Windows runner, because
    ## go dependencies are stored pernamently on this machine.
    ## This also fixes 'Permission denied' issues while using gitlab cache.
    
## Define the default test parameters.
.default_test: &default_test_params
  ## Merge the contents of the 'default_params' alias
  <<: *default_params
  stage: test

  ## disable default tests for scheduled pipelines (nightlies)
  except:
    - schedules

## Define the default test parameters
## for Windows runner.
.default_windows_test: &default_test_windows_params
  ## Merge the contents of the 'default_windows_params' alias
  <<: *default_windows_params
  stage: test
  tags:
    - nebulous-windows

  ## disable default tests for scheduled pipelines (nightlies)
  except:
    - schedules

## Define the default nightly test parameters.
.default_nightly_test: &default_nightly_params
  <<: *default_test_params
  ## Only run during scheduled pipelines.
  except:
   -  ""
  only:
   - schedules

  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always

  after_script:
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

## Define the default nightly test parameters
## for Windows runner.
.default_nightly_windows_test: &default_nightly_windows_params
  <<: *default_test_windows_params
  ## Only run during scheduled pipelines.
  except:
   -  ""
  only:
   - schedules

  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always

  after_script:
    - XCOPY "C:\Windows\Temp\SiaTesting\*" "$CI_PROJECT_DIR\SiaTesting" /S /I /Y > $null

build:
  stage: lint
  ## go 1.13 is the minimum accepted version for building Sia.
  image: golang:1.13
  artifacts:
    name: "Binaries"
    paths:
      - $CI_PROJECT_DIR/artifacts
  script:
    - ./check-builds.sh

siatest-tests-nightly:
  <<: *default_params
  script:
    - make test-vlong run=TestGlobalRatelimitRenter pkgs="./siatest/daemon"

